export const ADD_TASKS = 'ADD_TASKS';

export const CLOSE_DRAWER = 'CLOSE_DRAWER';

export const COMPLETE_TASKS = 'COMPLETE_TASKS';

export const DONE_FETCHING_FACETTED_SEARCH_OPTIONS = 'DONE_FETCHING_FACETTED_SEARCH_OPTIONS';

export const OPEN_DRAWER = 'OPEN_DRAWER';

export const REMOVE_ALL_TASKS = 'REMOVE_ALL_TASKS';

export const SET_FACETTED_SEARCH_OPTIONS = 'SET_FACETTED_SEARCH_OPTIONS';

export const START_FETCHING_FACETTED_SEARCH_OPTIONS = 'START_FETCHING_FACETTED_SEARCH_OPTIONS';

export const TOGGLE_FACETTED_SEARCH_ITEM = 'TOGGLE_FACETTED_SEARCH_ITEM';

export const TOGGLE_FACETTED_SEARCH_RELATION = 'TOGGLE_FACETTED_SEARCH_RELATION';
